apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: py-wallet-dev

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- migrate-job.yaml
- serviceaccount.yaml
- servicemonitor.yaml
- sealed-snapshot-service-secrets.yaml

images:
- name: ghcr.io/amysyutin/py_wallet-snapshot-service
  newName: ghcr.io/amysyutin/py_wallet-snapshot-service
  newTag: c602a39f689ba4b3a6c2db86459f3eaedcdf4452
