apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: py-wallet-dev

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- migrate-job.yaml
- serviceaccount.yaml
- servicemonitor.yaml
- sealed-snapshot-service-secrets.yaml

images:
- name: ghcr.io/amysyutin/py_wallet-snapshot-service
  newName: ghcr.io/amysyutin/py_wallet-snapshot-service
  newTag: 40856af5985f451b76736c7227c2bdb41baf416e
