apiVersion: batch/v1
kind: Job
metadata:
  name: py-wallet-snapshot-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"

spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/amysyutin/py_wallet-snapshot-service
          imagePullPolicy: Always
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: py-wallet-snapshot-service-secrets
                  key: DATABASE_URL
