---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: py-wallet-snapshot-service-secrets
  namespace: py-wallet-dev
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    DATABASE_URL: AgBshrYgvZqJ7hIB5fmL/UNViaSPt1vSkSuzSjlOqHGd/ueN+at84s99WsCdIRpE+8ta1bjbqzaRa4TzF3lheiIvTo5O0TBq26TnRIS0qkS1ygtsGHgcywg1icZ2rzBCn6E+cFgIrhCuOJOI4dge+C51GsiYsvKGq2LOnXhwMPCiwRLpC4eekVAe2SL+LMqNj+WJo3bonhhq25klwhig+I9GNuNWCMywl68x5kL3osGl7hIvnrHuSxLVauIfJMrCl+vg1AKt8tr+TEc49bXBxz/vIjf7zvB4+QnZcY+dTvnQUOGg8YKye3Z1/CebUO+zq6Y2PzbVo8rzvowUE7tGL9bm81bibQWFjNy/fpq+6+ZeLCgYIzX14vVzITpajJCoF1Tw1yDrO6drIYttdWYIOMm/qYeooxq0/Rc+6O0dTC+nhvQzTkfu7lQ8QLOnoSA0zHcvZO0ZUV5kr1SSRtP29WxSV+SAegech/IgiUInr3mAjW+eI1rFQL5zo1++FSTTpPtP2rupUy0WStoXLNcHMrJl5XbiGaQwiq3pGnGkptjkjLb87pJWK2XxCpa+ovRoA9QOk/vpI8b+2/P6cVEFuUYaSvB8VIcPu6zNQeWrsS+P738Z1XV/J0Yoie4rm3WXO1M0ntexmKhUXoOZGaFM4C7LNQHuVAKr1Y2Mb2329UWWYVCOXXh9yJwlVFIQrlqwcOFnjabMo7AFK6c9W42ZgxqQXs/1ROz1PW9TZVqgq9fzX5zA3Qi9DoyFA5OIWgqQ27wa/m/dKyjCQFEhu+NClFbrZddCJthT5ga1p+g8RKErbZ2kRIDlS4uMcPCG7HBt5zQ+2kL4W6gM3dVm
    INTERNAL_API_TOKEN: AgAb89puYKyOgtNgzXI0vkypdrEyXI36F6s+5psDYLGf8nXAjst6HnSBMttZuRbYvlNBfu8RsU5YeoF20ZihXJ+bLtNgxcuZlg7tbF9ZD0IS0+qLSMKKfOj3NVKKLIbAdVGyQalPRj0LyDC1o5F4XlUBNj6aZwv+pDu4bH9OSYQ2UXZjjGCyCqOXNPT9Ftiy+XjQiAZOyQcT3jGGb3+igc+H8c9icv49g78yT/bTgX0r20RDUhUyJ1WCNVt/F60fKSBC0EamlKc8QAk74/AJ97Cs/sFDDjbEIjr2oVsLWN1KLK25XrfSmPfPBJZmTDFwHduPTFkDcWkJnW9RTyVUSWGMBTTYwNPyhVVTvqdWdpfVq6ilDwjCyP3OAK9B9o/8zSnznKeXL32ygQlRUjvX49m9k7c7pCQ+FtlgYfCbi9Xdx7sRSVWh/pmUB5/HIOM175tKArZnvVK7M/VNN3yUpntqETUQdawdvb4+n/xLcRSyHbEYHV1lKJTm1cKaDrZ1xGgQeoSFDeKOKVlsSGue8hZFCiIjRUL3DYoqA0R7EoZVaFXSkbki0LjnBME0F0V3mBtO2sSyBGQJUYbAlRFDLDkCvh+6JZwoHZFBI44S9RN/RpRu0KlGQ/GRh8tyNyJCapmUVo7aa/QW26jIhaAS/EqIwSXR7YrodQX2S2Zn2OngP6UPG/DZ/8CE+vfnDh9GFw9QTD1pQtREGiV7rXiSMq5sAMG9RDvKksjdkHkKLUtl5x2AoTAOWkeN2iNQLFQ/z4Gc1KxxyqE1EsjhvzN8j1Jz
  template:
    metadata:
      name: py-wallet-snapshot-service-secrets
      namespace: py-wallet-dev
