apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: py-wallet-dev

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

images:
- name: ghcr.io/amysyutin/py_wallet
  newName: ghcr.io/amysyutin/py_wallet
  newTag: 0aa698ab6b8e3ce6981293e4bac9f38175c202d1

labels:
- includeTemplates: true
  pairs:
    app.kubernetes.io/environment: dev
    app.kubernetes.io/name: py-wallet
    app.kubernetes.io/part-of: py-wallet

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- certificate.yaml
- middleware-redirect-https.yaml
- configmap.yaml
- migrate-job.yaml
- serviceaccount.yaml
- servicemonitor.yaml