apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: py-wallet-dev

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

images:
- name: ghcr.io/amysyutin/py_wallet
  newName: ghcr.io/amysyutin/py_wallet
  newTag: 2ff8b8bb5a0156aafd353609e391bfac1b4bbfac

labels:
- includeTemplates: true
  pairs:
    app.kubernetes.io/environment: dev
    app.kubernetes.io/name: py-wallet
    app.kubernetes.io/part-of: py-wallet

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- certificate.yaml
- middleware-redirect-https.yaml
- configmap.yaml
- migrate-job.yaml
- serviceaccount.yaml
- servicemonitor.yaml
- sealed-py-wallet-secrets.yaml
