apiVersion: batch/v1
kind: Job
metadata:
  name: py-wallet-migrate
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: py-wallet-secrets
            - configMapRef:
                name: py-wallet-config