apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: py-wallet
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: py-wallet
  endpoints:
    - port: http
      path: /metrics
      interval: 30s