apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: py-wallet-dev

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: ghcr.io/amysyutin/py_wallet-front
  newName: ghcr.io/amysyutin/py_wallet-front
  newTag: 1e0b2187e8fccc82f4cde7f4a05f87cfba7b2d28
