apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: py-wallet-dev

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: ghcr.io/amysyutin/py_wallet-front
  newName: ghcr.io/amysyutin/py_wallet-front
  newTag: 4621b8241e009d4f0dc0db76876e7c094a992bc5
