apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py-wallet
  namespace: argocd
spec:
  project: py-wallet-runtime
  source:
    path: manifests/app
    repoURL: https://github.com/amysyutin/py_wallet-infra.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: py-wallet-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
